apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zdw1fyvmz-go 
  janus-idp.io/tekton: zdw1fyvmz-go
  backstage.io/kubernetes-id: zdw1fyvmz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zdw1fyvmz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml